export default [
  {
    id: 1,
    image: "/uploads/1730161058383.png",
    season: "",
    category: "Tops, Long Sleeve",
    color: "White",
    material: "Cotton",
    pattern: "Solid",
    tags: "",
    notes: "",
  },
  {
    id: 2,
    image: "/uploads/1730155559643.png",
    season: "",
    category: "Bottoms, Skirt",
    color: "Gray",
    material: "",
    pattern: "Solid",
    tags: "",
    notes: "",
  },
  {
    id: 3,
    image: "/uploads/1730155572000.png",
    season: "",
    category: "Bottoms, Pants",
    color: "Blue",
    material: "Denim",
    pattern: "Solid",
    tags: "",
    notes: "",
  },
  {
    id: 4,
    image: "/uploads/1730155584470.png",
    season: "",
    category: "Accessories, Belt",
    color: "Black, Silver",
    material: "Leather",
    pattern: "Solid",
    tags: "",
    notes: "",
  },
  {
    id: 5,
    image: "/uploads/1730154651434.png",
    season: "",
    category: "Tops, Long Sleeve",
    color: "Pink",
    material: "",
    pattern: "Solid",
    tags: "",
    notes: "",
  },
  {
    id: 6,
    image: "/uploads/1730155619122.png",
    season: "",
    category: "Outerwear, Coat",
    color: "Gray",
    material: "Wool",
    pattern: "Glen plaid",
    tags: "",
    notes: "",
  },
  {
    id: 7,
    image: "/uploads/1730155534982.png",
    season: "",
    category: "Bottoms, Skirt",
    color: "Pink",
    material: "",
    pattern: "Solid",
    tags: "",
    notes: "",
  },
  {
    id: 8,
    image: "/uploads/1730155516998.png",
    season: "",
    category: "Bags, Purse",
    color: "Black",
    material: "",
    pattern: "Solid",
    tags: "",
    notes: "",
  },
  {
    id: 9,
    image: "/uploads/1730155505404.png",
    season: "",
    category: "Bags, Purse",
    color: "White, Blue",
    material: "",
    pattern: "Floral",
    tags: "",
    notes: "",
  },
  {
    id: 10,
    image: "/uploads/1730155491548.png",
    season: "",
    category: "Accessories, Scarf",
    color: "Red",
    material: "",
    pattern: "Solid",
    tags: "",
    notes: "",
  },
  {
    id: 11,
    image: "/uploads/1730155455488.png",
    season: "",
    category: "Bottoms, Shorts",
    color: "Navy blue",
    material: "",
    pattern: "Solid",
    tags: "Athletic",
    notes: "",
  },
  {
    id: 12,
    image: "/uploads/1730155441383.png",
    season: "",
    category: "Tops, Long Sleeve",
    color: "Beige",
    material: "",
    pattern: "Solid",
    tags: "Athletic",
    notes: "",
  },
  {
    id: 13,
    image: "/uploads/1730155381643.png",
    season: "",
    category: "Shoes, Sneakers",
    color: "Beige",
    material: "",
    pattern: "",
    tags: "Athletic",
    notes: "",
  },
  {
    id: 14,
    image: "/uploads/1730155367830.png",
    season: "",
    category: "Tops, Long Sleeve",
    color: "White",
    material: "",
    pattern: "Solid",
    tags: "",
    notes: "",
  },
  {
    id: 15,
    image: "/uploads/1730155429796.png",
    season: "",
    category: "Bottoms, Pants",
    color: "Brown",
    material: "",
    pattern: "Solid",
    tags: "",
    notes: "",
  },
  {
    id: 16,
    image: "/uploads/1730155322305.png",
    season: "",
    category: "Shoes, Heels",
    color: "Red",
    material: "",
    pattern: "Solid",
    tags: "",
    notes: "",
  },
  {
    id: 17,
    image: "/uploads/1730155289759.png",
    season: "",
    category: "Tops, Short Sleeve",
    color: "Green",
    material: "",
    pattern: "Solid",
    tags: "",
    notes: "",
  },
  {
    id: 18,
    image: "/uploads/1730155308156.png",
    season: "",
    category: "Shoes, Boots",
    color: "Black",
    material: "Leather",
    pattern: "Solid",
    tags: "",
    notes: "",
  },
  {
    id: 19,
    image: "/uploads/1730155224207.png",
    season: "",
    category: "Dress",
    color: "Black, White",
    material: "",
    pattern: "Floral",
    tags: "",
    notes: "",
  },
  {
    id: 20,
    image: "/uploads/1730156147809.png",
    season: "Winter",
    category: "Outerwear, Puffer",
    color: "Navy blue",
    material: "",
    pattern: "Solid",
    tags: "",
    notes: "",
  },
  {
    id: 21,
    image: "/uploads/1730155240757.png",
    season: "",
    category: "Accessories, Hair",
    color: "Red",
    material: "",
    pattern: "Solid",
    tags: "Bow",
    notes: "",
  },
];
